### ISSUE TITLE
Uncaught SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by blowsie** [shakyShane/browser-sync-client#45]
When using `browser-sync-client.js?v=2.23.3:89` & Chrome latest.

I get the following error in the browser console.
`Uncaught SyntaxError: Unexpected token }`
I have used previous versions without issue. 

Could this be an issue in the source code?

**Comment by blowsie** [comment]
My last known working version is `2.18.13`

**Comment by loginov-rocks** [comment]
@blowsie same here, returned to the `2.18.13` too, waiting for fix.

**Comment by HugoPoi** [comment]
I have test all version, the bug is introduce in `2.22.0` of browser-sync but the bug is in the client so only one commit beeing issued 8ea3496a7af2f4b4674a5a56b08e206134dd2179

**Comment by johanberonius** [comment]
I got this error too and figured out that `browser-sync-client.js` ends with the line `//# sourceMappingURL=index.min.js.map` but no newline after that.

When other plugins concatenate to that script the first line of the plugin script get corrupted.

For example, with `browser-sync-ui` the line becomes `//# sourceMappingURL=index.min.js.map"use strict";` but the rest of the script till works.

But with `browser-sync-spa` the line becomes `//# sourceMappingURL=index.min.js.map(function (bs) {` and the rest of the script breaks.

**Comment by shakyShane** [comment]
This is fixed in browser-sync@2.23.6

Also, this repo is no longer used for the client development - it's under browser-sync now :)

**Comment by blowsie** [comment]
@shakyShane , Ok thanks I guess it makes sense to update the readme accordingly.
